name: Publish to Github Pages

on:
  push:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npx build-storybook

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.0.1
        with:
          build_dir: storybook-static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
